name: Blue Sky News Scanner

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Blue Sky News Scan
        run: |
         curl -fsS -X POST "postgresql://blue_sky_news_db_user:ceCW2XxUG3GoRUPGv3snf38jBfsdd1jZ@dpg-da83qdrbc2fs73cn17ig-a/blue_sky_news_db"
