name: Blue Sky News Scanner

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run Blue Sky News Scan
        run: |
         curl -fsS -X POST "https://blue-sky-news-backend.onrender.com/api/scan"
"
